// SPDX-License-Identifier: GPL-3.0-or-later
/**
    Note for the non-lawyers: The licence says that, if you fork:
    - The source code is made available to the public in source code form under the same license
    - The original author (@yakito_ri) must be attributed
**/

import "./jetton-wallet.tact";

// This is a mock contract to test the JettonizedVault contract
contract MockProtocol {
    
}